### ISSUE TITLE
Fix horizontal scrolling on screen.

### ISSUE THREAD

**Issue by vid277** [vid277/JHMC-scripts#3]
Fix horizontal scrolling caused as a result of adding the large AMS logo to the footer. 

- Remove AMS from the "big 3" at the bottom and place it with the other sponsors. 
- Don't simply disable horizontal scrolling.
- Fix scaling when viewing it on smaller screens that cause the logos to clip.

**Comment by vid277** [comment]
@michaelm0777

**Comment by michaelm0777** [comment]
Edits made in revamp branch
